[development]
network = { name = "local", run_locally = true }
accounts = ["admin"]

[development.contracts.invoice_registry]
client = true

[production]
network = { name = "futurenet" }
accounts = ["bob"]

[production.contracts.invoice_registry]
client = true
